"""Application contracts shared across layers."""

from app.contracts.messages import (
    APP_ERROR_DETECTED_TOPIC,
    DISCORD_CHAT_REPLY_READY_TOPIC,
    DISCORD_CHAT_SAVED_TOPIC,
    LINE_CHAT_REPLY_READY_TOPIC,
    LINE_CHAT_SAVED_TOPIC,
    GeneratedContent,
    MemoryContextPack,
    MemoryEntity,
    MemoryProfile,
    MemoryTimelineEntry,
    build_app_error_detected_payload,
    build_discord_chat_saved_payload,
    build_line_chat_saved_payload,
    build_reply_ready_payload,
    reply_topic_for,
)
from app.contracts.ports import (
    AIServiceError,
    EventHandler,
    IAIService,
    IEventBus,
    IMemoryService,
    MemoryServiceError,
)

__all__ = [
    "AIServiceError",
    "APP_ERROR_DETECTED_TOPIC",
    "DISCORD_CHAT_REPLY_READY_TOPIC",
    "DISCORD_CHAT_SAVED_TOPIC",
    "EventHandler",
    "GeneratedContent",
    "MemoryContextPack",
    "MemoryEntity",
    "MemoryProfile",
    "MemoryTimelineEntry",
    "IAIService",
    "IEventBus",
    "IMemoryService",
    "LINE_CHAT_REPLY_READY_TOPIC",
    "LINE_CHAT_SAVED_TOPIC",
    "MemoryServiceError",
    "build_app_error_detected_payload",
    "build_discord_chat_saved_payload",
    "build_line_chat_saved_payload",
    "build_reply_ready_payload",
    "reply_topic_for",
]
